pool:
  vmImage: windows-2022

trigger:
  branches:
    include:
    - main

stages:
- stage: TestTemplates
  jobs:

    - job: BuildTestAndPublish
      displayName: Build Function App, Test and publish ARM templates
      steps:
      - task: AzurePowerShell@4
        displayName: 'Test ARM templates'
        inputs:
          azureSubscription: 's255d.azdo.deployment'
          scriptType: filePath
          scriptPath: '$(System.DefaultWorkingDirectory)\Scripts\Test-ArmTemplate.ps1'
          scriptArguments: -ResourceGroup 's255d01rg-uks-tpltest01' -BaseDirectory '$(System.DefaultWorkingDirectory)\ARMTemplates' -Verbose
          azurePowerShellVersion: LatestVersion

      - task: PublishPipelineArtifact@1
        displayName: Publish Pipeline Artifact
        inputs:
          artifactName: 'DigitalForms.ArmTemplates.Shared'
          targetPath: '$(System.DefaultWorkingDirectory)\ARMTemplates'

      - task: PublishPipelineArtifact@1
        displayName: Publish Scripts Artifact
        inputs:
          artifact:  'DigitalForms.Scripts'
          targetPath: '$(System.DefaultWorkingDirectory)\scripts'

      - task: ArchiveFiles@2
        displayName:  Archive function app
        inputs:
          rootFolderOrFile: '$(Build.SourcesDirectory)/functions/DigitalForms.Platform.Monitoring.Functions'
          includeRootFolder: false
          archiveType: zip
          archiveFile: '$(Build.ArtifactStagingDirectory)/DigitalForms.Platform.Monitoring.Functions.zip'

      - task: PublishPipelineArtifact@1
        displayName: Publish function app
        inputs:
          artifactName: 'DigitalForms.Functions.Monitoring'
          targetPath: '$(Build.ArtifactStagingDirectory)/DigitalForms.Platform.Monitoring.Functions.zip'


- stage: DeployToDev
  condition: succeeded('TestTemplates')
  variables:
  - template: VariableTemplates\dev.yml
  - template: VariableTemplates\shared.yml
  - group: "Digital Forms - EAPIM Configuration - Dev"
  - group: "Digital Forms - Sql Server Configuration - Dev"
  jobs:
  - template: JobTemplates\deploy.yml
    parameters:
      AzureServiceConnection: 's255d.azdo.deployment'
      Environment: Dev

- stage: DeployToTest
  condition: and(succeeded(), or(eq(variables['Build.SourceBranch'], 'refs/heads/main'), startsWith(variables['Build.SourceBranch'], 'refs/heads/release/')))
  variables:
  - template: VariableTemplates\test.yml
  - template: VariableTemplates\shared.yml
  - group: "Digital Forms - EAPIM Configuration - Test"
  - group: "Digital Forms - Sql Server Configuration - Test"
  jobs:
  - template: JobTemplates\deploy.yml
    parameters:
      AzureServiceConnection: 's255t.azdo.deployment'
      Environment: Test

- stage: DeployToPreProduction
  condition: and(succeeded(), or(eq(variables['Build.SourceBranch'], 'refs/heads/main'), startsWith(variables['Build.SourceBranch'], 'refs/heads/release/')))
  variables:
  - template: VariableTemplates\preprod.yml
  - template: VariableTemplates\shared.yml
  - group: "Digital Forms - EAPIM Configuration - PreProduction"
  - group: "Digital Forms - Sql Server Configuration - PreProduction"
  jobs:
  - template: JobTemplates\deploy.yml
    parameters:
      AzureServiceConnection: 's255t.azdo.deployment'
      Environment: PreProduction

- stage: DeployToDataScience
  condition: and(succeeded(), or(eq(variables['Build.SourceBranch'], 'refs/heads/main'), startsWith(variables['Build.SourceBranch'], 'refs/heads/release/')))
  variables:
  - template: VariableTemplates\datasci.yml
  - template: VariableTemplates\shared.yml
  - group: "Digital Forms - EAPIM Configuration - DataScience"
  - group: "Digital Forms - Sql Server Configuration - DataScience"
  jobs:
  - template: JobTemplates\deploy.yml
    parameters:
      AzureServiceConnection: 's255t.azdo.deployment'
      Environment: DataScience

- stage: DeployToProduction
  condition: and(succeeded(), or(eq(variables['Build.SourceBranch'], 'refs/heads/main'), startsWith(variables['Build.SourceBranch'], 'refs/heads/release/')))
  variables:
  - template: VariableTemplates\prod.yml
  - template: VariableTemplates\shared.yml
  - group: "Digital Forms - EAPIM Configuration - Production"
  - group: "Digital Forms - Sql Server Configuration - Production"
  jobs:
  - template: JobTemplates\deploy.yml
    parameters:
      AzureServiceConnection: 's255p.azdo.deployment'
      Environment: Production
